apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  namespace: jenkins
  labels:
    app: task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: magedsopihy/task:<TAG>
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task      
  name: task
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: task
  type: LoadBalancer         