variable "VPC_NAME" {}
variable "VPC_CIDR_BLOCK" {}
variable "PRIVATE_SUBNET_CIDR" {}
variable "PUBLIC_SUBNET_CIDR" {}
variable "CLUSTER_NAME" {}
variable "INSTANCE_TYPE" {}
variable "DESIRED_CAPACITY" {}
variable "REGION" {}
variable "MAX_CAPACITY" {}
variable "MIN_CAPACITY" {}
variable "VOLUME_TYPE" {}
variable "VOLUME_SIZE" {}
variable "LOGS_TYPES" {}
