---
- hosts: localhost
  tasks:
  - name: Create a k8s namespace for jenkins
    k8s:
      name: jenkins
      api_version: v1
      kind: Namespace
      state: present

  - name: Create a service Accouunt for jenkins 
    k8s:
      state: present
      src: ./serviceAccount.yaml   
  
  - name: Create a volume for jenkins pod 
    k8s:
      state: present
      src: ./volume.yaml   
      
  - name: Create a configmap for jenkins plugins
    k8s:
      state: present
      src: ./config.yaml

  - name: Create a Deployment for node app 
    k8s:
      state: present
      src: ./deployment.yaml



  - name: expose jenkins via loadblancer 
    k8s:
      state: present
      src: ./service.yaml   

