# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: jenkins-admin
# rules:
#   - apiGroups: ["*"]
#     resources: ["*"]
#     verbs: ["*"]

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: jenkins-admin
#   namespace: jenkins

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: jenkins-admin
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: jenkins-admin
  
# subjects:
# - kind: ServiceAccount
#   name: jenkins-admin
#   namespace: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin-clusterrole
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-admin-clusterrole
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "watch", "list"]  